<?php
  $lang['number']		= 'Invoice #';
  $lang['po_number']	= 'PO #';
  $lang['date'] 		= 'Invoice Date';
  $lang['time']			= 'Invoice Time';
  $lang['due'] 			= 'Payment Due';
  $lang['to'] 			= 'Billing to';
  $lang['from'] 		= 'Billing from';
  $lang['period'] 		= 'Billing Period';
  $lang['product'] 		= 'Services';
  $lang['total_qty']    = 'Hrs Total';
  $lang['qty'] 			= 'Hrs';
  $lang['price'] 		= 'Rate';
  $lang['price_ot'] 	= 'OT Rate';
  $lang['quantity_ot'] 	= 'OT Hrs';
  $lang['total'] 		= 'Total';
  $lang['grand_total'] 	= 'Grand Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>
