<?php
  $lang['number']		= 'Invoice #';
  $lang['date'] 		= 'Invoice Date';
  $lang['time']			= 'Invoice Time';
  $lang['due'] 			= 'Payment Due';
  $lang['to'] 			= 'Billing to';
  $lang['from'] 		= 'Billing from';
  $lang['product'] 		= 'Services';
  $lang['qty'] 			= 'Hours';
  $lang['price'] 		= 'Price';
  $lang['price_ot'] 	= 'OT Price';
  $lang['quantity_ot'] 	= 'OT Hours';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>
